#!/usr/bin/env bash
$sdk/sbf 
$@"; do if 
[[ $a = --sbf-sdk ]]; then   
sbf_sdk= 
fi  
export
\ CARGO_BUILD_SBF="/cargo-build-sbf
set -x exec cargo run --manifest-path "$sdk/cargo-test-sbf/Cargo.toml -- $sbf_sdk "$@"
