name: release-artifacts-auto
on:
  push:
    branches:
      - master
      - v[0-9]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  release-artifacts:
    if: github.repository == 'solana-labs/solana'
    uses: ./.github/workflows/release-artifacts.yml
    with:
      commit: ${{ github.sha }}
  error_reporting:
    if: failure() && github.event_name == 'push'
    uses: ./.github/workflows/error-reporting.yml
